// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5wOiVFlGrdAW_YmxZWLERmeyQK_NpSvE',
    appId: '1:424141655125:web:fe094cb247cb2012ac18dc',
    messagingSenderId: '424141655125',
    projectId: 'ghmc-officer',
    authDomain: 'ghmc-officer.firebaseapp.com',
    storageBucket: 'ghmc-officer.appspot.com',
    measurementId: 'G-KL5N4P0NVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-K8Jo_YVpGjusi07EXQkU9MIRytts5Kc',
    appId: '1:424141655125:android:8bd42325bf7a37e9ac18dc',
    messagingSenderId: '424141655125',
    projectId: 'ghmc-officer',
    storageBucket: 'ghmc-officer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8i7SYBUYMGpfQ3W7sbYF4DgxWBwLlU6U',
    appId: '1:424141655125:ios:fc52188a6c6ae6f5ac18dc',
    messagingSenderId: '424141655125',
    projectId: 'ghmc-officer',
    storageBucket: 'ghmc-officer.appspot.com',
    iosClientId: '424141655125-pkfu2rl9rcshqb566k5a013k03hdpnim.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghmcOfficer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8i7SYBUYMGpfQ3W7sbYF4DgxWBwLlU6U',
    appId: '1:424141655125:ios:fc52188a6c6ae6f5ac18dc',
    messagingSenderId: '424141655125',
    projectId: 'ghmc-officer',
    storageBucket: 'ghmc-officer.appspot.com',
    iosClientId: '424141655125-pkfu2rl9rcshqb566k5a013k03hdpnim.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghmcOfficer',
  );
}
